version: '3.7'

services:

  ievtds:
    container_name: ievtds
    build:
      dockerfile: fpm.Dockerfile
      context: .
    volumes:
      - ievtds-data:/var/www/html
    restart: unless-stopped
    env_file:
      - env/run.env
    environment:
      - ievtds_SETUP
    depends_on:
      - ievtds-db

  ievtds-proxy:
    image: nginx:1.19.0
    ports:
      - 8080:80
    depends_on:
      - ievtds
    volumes:
      - ievtds-data:/var/www/html
      - ./nginx/templates:/etc/nginx/templates

  ievtds-db:
    container_name: ievtds-db
    image: mariadb
    volumes:
      - ievtds-db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - env/db.env

volumes:
  ievtds-data:
  ievtds-db:
